require_relative '../node_modules/react-native/scripts/react_native_pods'

# REQUIRED for react-native-firebase + gRPC stability
$RNFirebaseAsStaticFramework = true

platform :ios, '16.0'

prepare_react_native_project!

target 'KandiNFC' do
  config = use_native_modules!

  # Firebase MUST be static frameworks
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Apple Silicon simulator fix (M1/M2/M4)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
